---
- name: core schema update 
  shell: python3 /data-act/backend/dataactbroker/scripts/initialize.py -d
  sudo: true
  environment:
    PYTHONPATH: "/data-act/backend"
  args:
    chdir: /data-act/backend/dataactbroker/scripts/
