---
- hosts: govcloud_instance_launch
  user: ec2-user
  roles:
    - copy-files
    - { role: fsrs-cron, when: APP == "jobmgr"}
    - { role: start-server, when: APP != "jobmgr"}
    - { role: start-jobmgr, when: APP == "jobmgr"}
    - start-new-relic
  environment:
    env: "{{ ENV }}"