---
- hosts: "{{ HOST }}"
  user: ec2-user
  become_method: sudo
  roles:
  - pull-repo
  - install-requirements
  vars:
    REPO: https://github.com/fedspendingtransparency/data-act-broker-backend.git

  tasks:
    # setup supervisord.service
    - name: make supervisord.service directory
      become: true
      file:
        path: /etc/supervisord/conf.d
        recurse: true
        state: directory

    - name: supervisord.service conf
      become: true
      shell: echo_supervisord_conf > /etc/supervisord/supervisord.conf

    - name: supervisord.service conf.d append
      become: true
      shell: echo "files = conf.d/*.conf" >> /etc/supervisord/supervisord.conf

    - name: supervisord.service config file location (validator)
      when: APP == 'validator'
      become: true
      replace:
        dest: "/data-act/data-act-broker-config/supervisord.service/supervisord.service"
        regexp: 'ExecStart=/bin/supervisord.*'
        replace: "ExecStart=/bin/supervisord -c /data-act/backend/dataactvalidator/config/supervisord.conf"

    - name: supervisord.service copy
      become: true
      copy:
        remote_src: true
        src:  "/data-act/data-act-broker-config/supervisord.service/supervisord.service"
        dest: "/usr/lib/systemd/system/supervisord.service"
        