---
- hosts: govcloud_instance_image
  user: ec2-user
  roles:
  - pull-repo
  - pip-install
  - add-hostfile
  vars:
    REPO: https://github.com/fedspendingtransparency/data-act-broker-backend.git
    