# Base Ansible to run on a fresh RHEL7 install.
# Installs Jenkins dependencies. 
# This playbook is for BUILD-Jenkkins 

---
- hosts: "{{ HOST }}"

  become_method: sudo

  user: ec2-user

  tasks:

    - name: upgrade all packages
      become: true
      yum: name=* state=latest

    - name: install EPEL and IUS repos
      become: true
      yum: name={{ item }}
      with_items:
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        - https://centos7.iuscommunity.org/ius-release.rpm

    - name: install base dependencies
      become: true
      yum: name={{ item }}
      with_items:
        - ansible
        - gcc
        - gcc-c++
        - git
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel.x86_64
        - pcre.x86_64
        - pcre-devel.x86_64
        - postgresql-devel.x86_64
        - python-devel.x86_64
        - python-pip
        - python35u
        - python35u-devel 
        - python35u-libs
        - python35u-pip
        - unzip
        - wget
        - zlib-devel
        - mlocate
        - vim
        - telnet

    - name: install all pip packages
      become: true
      pip: 
        name: "{{ item }}"
        state: present
        executable: pip
      with_items:
        - awscli
        - boto
        - boto3
        - sh
        - python-packer
        - wheel
        - virtualenv-clone

    - name: install jenkins 
      become: true
      yum:
        name=https://pkg.jenkins.io/redhat-stable/jenkins-2.107.2-1.1.noarch.rpm

    - name: install filebeat (from filebeat repo)
      become: true
      yum: 
        name=https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.1.1-x86_64.rpm

    - name: create /terraform directory
      become: true
      file: 
        path: /terraform
        state: directory
        mode: 0755

    - name: download and unarchive terraform_0.6.16_linux_amd64.zip
      become: true
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.11.5/terraform_0.11.5_linux_amd64.zip
        dest: /terraform
        remote_src: yes

    - name: execute terraform
      become: true
      shell: /terraform/terraform init /terraform/

    - name: create /packer directory
      become: true
      file: 
        path: /packer
        state: directory
        mode: 0755

    - name: download and unarchive packer_1.2.3_linux_amd64.zip
      become: true
      unarchive:
        src: https://releases.hashicorp.com/packer/1.2.3/packer_1.2.3_linux_amd64.zip
        dest: /packer
        remote_src: yes

    - name: rename packer to packerio
      become: true
      shell: "mv /packer/packer /packer/packerio"

    - name: setup symbolic link
      become: true
      stat: 
        path=/usr/sbin/packerio
      register: links

    - name: check symbolic link
      debug: msg="Path exists and is a symlink"
      when: links.stat.islnk is defined and links.stat.islnk

    - name: show timestamp in history (root)
      become: true
      lineinfile: 
        dest: /root/.bash_profile
        line: "export HISTTIMEFORMAT=\"%d/%m/%y %T \""
        state: present

    - name: show timestamp in history (ec2-user)
      lineinfile: 
        dest: /home/ec2-user/.bash_profile
        line: "export HISTTIMEFORMAT=\"%d/%m/%y %T \""
        state: present

    - name: colorize (root)
      become: true
      lineinfile: 
        dest: /root/.bash_profile
        line: 'export PS1="[\[$(tput sgr0)\]\[\033[38;5;1m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\[$(tput sgr0)\]\[\033[38;5;45m\]\h\[$(tput sgr0)\]\[\033[38;5;15m\] \W]\\$ \[$(tput sgr0)\]"'
        state: present

    - name: colorize (ec2-user)
      lineinfile:
        dest: /home/ec2-user/.bash_profile
        line: 'export PS1="[\[$(tput sgr0)\]\[\033[38;5;11m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\[$(tput sgr0)\]\[\033[38;5;45m\]\h\[$(tput sgr0)\]\[\033[38;5;15m\] \W]\\$ \[$(tput sgr0)\]"'
        state: present

    - name: restart and enable jenkins service
      become: true
      shell: "systemctl enable jenkins && systemctl restart jenkins"

    - name: enable and restart filebeat 
      become: true
      shell: "systemctl enable filebeat && systemctl restart filebeat"
      
