---
- hosts: thingy
  user: ec2-user
  roles:
  - pull-repo
  - add-hostfile
  tasks:
    - name: update pip
      sudo: true
      shell: pip3.5 install --upgrade pip 
    - name: install python packages based on requirements.txt
      sudo: true
      pip: chdir=/data-act/backend requirements="requirements.txt" executable=pip3.5
    - name: install python packages based on server_requirements.txt
      sudo: true
      pip: chdir=/data-act/backend requirements="server_requirements.txt" executable=pip3.5
    - name: install python packages based on legacy_requirements.txt
      sudo: true
      pip: chdir=/data-act/backend requirements="legacy_requirements.txt" executable=pip2
    - name: copy nginx config
      sudo: true
      shell: cp /data-act/config/nginx/nginx_ds_api.conf /etc/nginx/nginx.conf 
    - name: duplicate config file to uwsgi_db.ini
      sudo: true
      shell: cp /data-act/backend/config/uwsgi.ini /data-act/backend/config/uwsgi_db.ini
    - name: copy user-level environment variable to temp text file...
      sudo: false
      shell: echo env=DATABASE_URL=$DATABASE_URL > /data-act/backend/config/temp.txt
    - name: concatenate the duplicate config and the env var
      sudo: true
      shell: cat /data-act/backend/config/temp.txt >> /data-act/backend/config/uwsgi_db.ini
    - name: add static url from s3
      lineinfile:
        dest: /data-act/backend/usaspending_api/settings.py
        regexp: '.*STATIC_URL =.*'
        line: "STATIC_URL = 'http://ds-api-assets.s3-website-us-gov-west-1.amazonaws.com/'"
    - name: stop supervisord
      shell: pkill supervisord
      sudo: true
      ignore_errors: yes    
    - name: start supervisord
      shell: supervisord -c /data-act/backend/config/supervisord.conf &
      sudo: true  
      environment:
          PYTHONPATH: "/data-act/backend"
      args:
          chdir: /data-act/backend/usaspending_api/  
  vars:
    REPO: https://github.com/fedspendingtransparency/usaspending-api.git
    BRANCH: "{{ BRANCH_EXTRA_VAR }}"
  