---
- hosts: "{{ HOST }}"

# Required: {{ BRANCH }}

  vars:
    REPO: https://github.com/fedspendingtransparency/usaspending-api.git

    ## Branch options: sandbox, dev, stg, master
    BRANCH: "{{ BRANCH }}"

    CODE_HOME: /data-act/backend
    CONFIG_HOME: /data-act/config

    REQ_DIR: "{{ CODE_HOME }}/requirements"

    CSV_S3_BUCKET_NAME: "{{ lookup('file', 'csv_s3_bucket_name') }}"
    CSV_SQS_QUEUE_NAME: "{{ lookup('file', 'csv_sqs_queue_name') }}"
    CSV_AWS_REGION: "{{ lookup('file', 'csv_aws_region') }}"

  become_method: sudo  

  user: ec2-user
  tasks:
    - name: Checkout backend from git
      become: true
      git: repo={{ REPO }}
           version={{ BRANCH }}  
           dest={{ CODE_HOME }}
           accept_hostkey=true 
           force=yes

    - name: Checkout config from git
      become: true
      git: repo=git@github.com:fedspendingtransparency/data-act-broker-config.git 
           dest={{ CONFIG_HOME }}
           accept_hostkey=true 
           force=yes 
           key_file="/home/ec2-user/.ssh/id_rsa"

    - name: update pip
      become: true 
      shell: pip3.5 install --upgrade pip 

    - name: copy requirements.txt (to check for changes)
      become: true 
      copy:
        src:  "{{ REQ_DIR }}/requirements.txt"
        dest: "{{ REQ_DIR }}/requirements_copy.txt"
        remote_src: true
      register: requirements_txt
    - name: install python packages based on requirements.txt
      become: true 
      when: requirements_txt.changed
      pip: chdir="{{ REQ_DIR }}" requirements="requirements.txt" executable=pip3.5

    - name: set starting directory to CODE_HOME
      become: true
      lineinfile: 
        dest: /home/ec2-user/.bashrc
        line: "cd {{ CODE_HOME }}"
        insertafter: EOF 

# usaspending_api/settings.py (for running the actual generate download command)

    - name: add CSV S3 name
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*CSV_S3_BUCKET_NAME =.*'
        line: "CSV_S3_BUCKET_NAME = '{{ CSV_S3_BUCKET_NAME }}'"

    - name: add CSV SQS url
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*CSV_SQS_QUEUE_NAME =.*'
        line: "CSV_SQS_QUEUE_NAME = '{{ CSV_SQS_QUEUE_NAME }}'"

    - name: add CSV AWS region
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*CSV_AWS_REGION =.*'
        line: "CSV_AWS_REGION = '{{ CSV_AWS_REGION }}'"

    - name: get DATABASE_URL env var
      shell: cat /etc/db_{{ BRANCH }}.sh
      register: DATABASE_URL_VAR

# Start Worker 

    - name: start csv_worker.py
      become: true
      shell: "nohup python3.5 -u manage.py generate_bulk_zip >> worker-out.txt 2>&1 &"
      environment:
        DATABASE_URL: "{{ DATABASE_URL_VAR.stdout }}"
        CSV_S3_BUCKET_NAME: "{{ CSV_S3_BUCKET_NAME }}"
        CSV_SQS_QUEUE_NAME: "{{ CSV_SQS_QUEUE_NAME }}"
        CSV_AWS_REGION: "{{ CSV_AWS_REGION }}"
      args:
        chdir: "{{ CONFIG_HOME }}/usaspending-csv"
