---
- name: install base dependencies
  sudo: true
  yum: name={{ item }}
  with_items:
    - python-devel.x86_64
    - python-pip
    - python35u
    - python35u-libs
    - python35u-devel 
    - python35u-pip
    - postgresql-devel.x86_64
    - gcc
    - gcc-c++
    - libffi-devel
    - pcre.x86_64
    - pcre-devel.x86_64

- name: install nginx (from nginx repo)
  sudo: true
  yum: 
    name=http://nginx.org/packages/mainline/centos/7/x86_64/RPMS/nginx-1.13.8-1.el7_4.ngx.x86_64.rpm

- name: install New Relic APM
  sudo: true
  pip: name=newrelic executable=pip3.5

- name: Download New Relic Infrastructure
  sudo: true
  shell: curl -o /etc/yum.repos.d/newrelic-infra.repo https://download.newrelic.com/infrastructure_agent/linux/yum/el/7/x86_64/newrelic-infra.repo

- name: Update cache for New Relic Infrastructure
  sudo: true
  shell: yum -q makecache -y --disablerepo='*' --enablerepo='newrelic-infra'

- name: Install New Relic Infrastructure
  sudo: true
  yum: name=newrelic-infra

# Activate the following if we want to update Broker's ELK

#- name: install filebeat (from filebeat repo)
#  sudo: true
#  yum: 
#    name=https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.1.1-x86_64.rpm
    
