---
- name: core schema update 
  shell: python /data-act/backend/dataactvalidator/scripts/initialize.py -d
  sudo: true
  environment:
    PYTHONPATH: "/data-act/backend"
  args:
    chdir: /data-act/backend/dataactvalidator/scripts/