---
- hosts: "{{ HOST }}"

# Required: {{ BULK_VARS_PREFIX }}, the prefix to the .yml with bulk download vars 
#           AND = the path to the DB URL, either dev or sandbox

  vars:
    BULK_VARS_PREFIX: "{{ BULK_VARS_PREFIX }}"
    CONFIG_HOME: '/data-act/config'
    
    REPO: https://github.com/fedspendingtransparency/usaspending-api.git
    CODE_HOME: '/data-act/backend'
    REQ_DIR: '{{ CODE_HOME }}/requirements'

  become_method: sudo  

  user: ec2-user
  tasks:  

    - name: Checkout usaspending-config from git
      become: true
      git: repo=git@github.com:fedspendingtransparency/usaspending-config.git
           dest={{ CONFIG_HOME }}
           accept_hostkey=true 
           force=yes 
           key_file="/home/ec2-user/.ssh/id_rsa_usaspending_config"

    - name: Load variables from config repo
      include_vars: "{{ BULK_VARS_PREFIX }}-bulk-download-vars-ansible.yml"

    - name: Checkout usaspending-api code from git
      become: true
      git: repo='https://github.com/fedspendingtransparency/usaspending-api.git'
           version={{ USASPENDING_API_BRANCH }}  
           dest={{ CODE_HOME }}
           accept_hostkey=true 
           force=yes

    - name: update pip
      become: true 
      shell: pip3.5 install --upgrade pip 

    - name: copy requirements.txt (to check for changes)
      become: true 
      copy:
        src:  "{{ REQ_DIR }}/requirements.txt"
        dest: "{{ REQ_DIR }}/requirements_copy.txt"
        remote_src: true
      register: requirements_txt
    - name: install python packages based on requirements.txt
      become: true 
      when: requirements_txt.changed
      pip: chdir="{{ REQ_DIR }}" requirements="requirements.txt" executable=pip3.5

    - name: copy legacy_requirements.txt (to check for changes)
      become: true
      copy:
        src:  "{{ REQ_DIR }}/legacy_requirements.txt"
        dest: "{{ REQ_DIR }}/legacy_requirements_copy.txt"
        remote_src: true
      register: legacy_requirements_txt
    - name: install python packages based on legacy_requirements.txt
      become: true
      when: legacy_requirements_txt.changed
      pip: chdir="{{ REQ_DIR }}" requirements="legacy_requirements.txt" executable=pip2

    - name: Copy New Relic package
      become: true
      shell: rpm -Uvh https://download.newrelic.com/pub/newrelic/el5/i386/newrelic-repo-5-3.noarch.rpm --replacefiles --replacepkgs
    - name: Install New Relic Sysmond
      become: true
      yum:
        name: newrelic-sysmond
        state: latest

    - name: set starting directory to CODE_HOME
      become: true
      lineinfile: 
        dest: /home/ec2-user/.bashrc
        line: "cd {{ CODE_HOME }}"
        insertafter: EOF


# newrelic settings

    - name: get contents of nr_key file
      command: cat /etc/nr_key
      register: NR_KEY

    - name: Set New Relic License Key
      become: true
      shell: nrsysmond-config --set license_key={{ NR_KEY.stdout }}


# usaspending_api/settings.py (for running the actual generate download command)

    - name: make ec2-user own everything
      become: true
      file: 
        path: /data-act
        state: directory
        owner: ec2-user
        mode: "u+wrx"
        recurse: true

    - name: add Bulk Download option
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*IS_LOCAL =.*'
        line: "IS_LOCAL = False"

    - name: add Bulk Download S3 name
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*BULK_DOWNLOAD_S3_BUCKET_NAME =.*'
        line: "BULK_DOWNLOAD_S3_BUCKET_NAME = '{{ BULK_DOWNLOAD_S3_BUCKET_NAME }}'"

    - name: add Bulk Download SQS url
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*BULK_DOWNLOAD_SQS_QUEUE_NAME =.*'
        line: "BULK_DOWNLOAD_SQS_QUEUE_NAME = '{{ BULK_DOWNLOAD_SQS_QUEUE_NAME }}'"

    - name: add Bulk Download AWS region
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*BULK_DOWNLOAD_AWS_REGION =.*'
        line: "BULK_DOWNLOAD_AWS_REGION = '{{ BULK_DOWNLOAD_AWS_REGION }}'"

    - name: get DATABASE_URL env var
      shell: cat /etc/db_{{ BULK_VARS_PREFIX }}.sh
      register: DATABASE_URL_VAR


# Start Worker

    - name: Run New Relic
      become: true
      shell: /etc/init.d/newrelic-sysmond start

    - name: stop supervisord
      become: true
      shell: pkill supervisord
      ignore_errors: true

    - name: start supervisord
      become: true
      shell: "supervisord -c {{ CODE_HOME }}/usaspending_api/bulk_download/config/supervisord.conf &"
      environment:
        PYTHONPATH: "{{ CODE_HOME }}"
        NUM_PROCS: "{{ NUM_PROCS }}"
        DATABASE_URL_VAR: "{{ DATABASE_URL_VAR.stdout }}"
      args:
        chdir: "{{ CODE_HOME }}/usaspending_api/"
