---
- hosts: "{{ HOST }}"

# Required: {{ BULK_VARS_PREFIX }}, the prefix to the .yml with bulk download vars 
#           AND = the path to the DB URL, either dev or sandbox

  vars:
    BULK_VARS_PREFIX: "{{ BULK_VARS_PREFIX }}"
    CONFIG_HOME: '/data-act/config'
    
    REPO: https://github.com/fedspendingtransparency/usaspending-api.git
    CODE_HOME: '/data-act/backend'
    REQ_DIR: '{{ CODE_HOME }}/requirements'
    
# Name mismatching from BULK_VARS_PREFIX (dev/sbx are same)
    env_mapping:
      prod: {alt_name: master}
      staging: {alt_name: stg}
      dev: {alt_name: dev}
      sandbox: {alt_name: sandbox}

  become_method: sudo  

  user: ec2-user
  tasks:  

    - name: copy git credentials from S3 Bucket
      shell: "aws s3 cp s3://da-config/usaspending/id_rsa_usaspending_config /home/ec2-user/.ssh/ --region us-gov-west-1"

    - name: Checkout usaspending-config from git
      become: true
      git: repo=git@github.com:fedspendingtransparency/usaspending-config.git
           version=master
           dest={{ CONFIG_HOME }}
           accept_hostkey=true 
           force=yes 
           key_file="/home/ec2-user/.ssh/id_rsa_usaspending_config"

    - name: Load variables from config repo
      include_vars: /{{ CONFIG_HOME }}/deploy/{{ BULK_VARS_PREFIX }}-bulk-download-vars-ansible.yml

    - name: Checkout usaspending-api code from git
      become: true
      git: repo='https://github.com/fedspendingtransparency/usaspending-api.git'
           version={{ USASPENDING_API_BRANCH }}  
           dest={{ CODE_HOME }}
           accept_hostkey=true 
           force=yes

    - name: update pip
      become: true 
      shell: pip3.5 install --upgrade pip 

    - name: install python packages based on requirements.txt
      become: true 
      pip: chdir="{{ REQ_DIR }}" requirements="requirements.txt" executable=pip3.5

    - name: install python packages based on legacy_requirements.txt
      become: true
      pip: chdir="{{ REQ_DIR }}" requirements="legacy_requirements.txt" executable=pip2

    - name: Copy New Relic package
      become: true
      shell: rpm -Uvh https://download.newrelic.com/pub/newrelic/el5/i386/newrelic-repo-5-3.noarch.rpm --replacefiles --replacepkgs
      
    - name: Install New Relic Sysmond
      become: true
      yum:
        name: newrelic-sysmond
        state: latest

    - name: set starting directory to CODE_HOME
      become: true
      lineinfile: 
        dest: /home/ec2-user/.bashrc
        line: "cd {{ CODE_HOME }}"
        insertafter: EOF

# copy New Relic License key from S3 Bucket

    - name: copy nr_key from S3
      become: true 
      shell: "aws s3 cp s3://da-config/shared/nr_key.yml /etc/ --region us-gov-west-1"

    - name: load nr_key var
      include_vars: /etc/nr_key.yml

# newrelic settings

    - name: set new relic license key
      become: true
      shell: nrsysmond-config --set license_key={{ NR_KEY }}

# usaspending_api/settings.py (for running the actual generate download command)

    - name: make ec2-user own everything
      become: true
      file: 
        path: /data-act
        state: directory
        owner: ec2-user
        mode: "u+wrx"
        recurse: true

    - name: add Bulk Download option
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*IS_LOCAL =.*'
        line: "IS_LOCAL = False"

    - name: add Bulk Download S3 name
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*BULK_DOWNLOAD_S3_BUCKET_NAME =.*'
        line: "BULK_DOWNLOAD_S3_BUCKET_NAME = '{{ BULK_DOWNLOAD_S3_BUCKET_NAME }}'"

    - name: add Bulk Download SQS url
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*BULK_DOWNLOAD_SQS_QUEUE_NAME =.*'
        line: "BULK_DOWNLOAD_SQS_QUEUE_NAME = '{{ BULK_DOWNLOAD_SQS_QUEUE_NAME }}'"

    - name: add Bulk Download AWS region
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*BULK_DOWNLOAD_AWS_REGION =.*'
        line: "BULK_DOWNLOAD_AWS_REGION = '{{ BULK_DOWNLOAD_AWS_REGION }}'"

    - name: download secrets from S3 bucket
      become: true
      shell: " aws s3 cp s3://da-config/usaspending/{{ BULK_VARS_PREFIX }}-usaspending-api-secrets.yml /etc/ --region us-gov-west-1"

    - name: load secrets 
      include_vars: /etc/{{ BULK_VARS_PREFIX }}-usaspending-api-secrets.yml

# Start Worker

    - name: Run New Relic
      become: true
      shell: /etc/init.d/newrelic-sysmond start

    - name: stop supervisord
      become: true
      shell: pkill supervisord
      ignore_errors: true

    - name: start supervisord
      become: true
      shell: "supervisord -c {{ CODE_HOME }}/usaspending_api/bulk_download/config/supervisord.conf &"
      environment:
        PYTHONPATH: "{{ CODE_HOME }}"
        NUM_PROCS: "{{ NUM_PROCS }}"
        DATABASE_URL_VAR: "{{ DB_SOURCE }}"
      args:
        chdir: "{{ CODE_HOME }}/usaspending_api/"
