# launch playbook for USASpending-ElasticSearch

---
- hosts: "{{ HOST }}"

  become_method: sudo

  user: ec2-user

  tasks:

# Copy Git Credentials from S3 Bucket

    - name: copy git credentials from S3 Bucket
      shell: "aws s3 cp s3://da-config/usaspending/id_rsa_usaspending_config /home/ec2-user/.ssh/ --region us-gov-west-1"

    - name: change mode for the id_rsa_usaspending_config
      become: true 
      file: 
        path: /home/ec2-user/.ssh/id_rsa_usaspending_config
        mode: 0400

# Git Checkout
    
    - name: checkout usaspending-config from git
      become: true
      git: repo=git@github.com:fedspendingtransparency/usaspending-config.git
           dest=/data-act/config
           accept_hostkey=true 
           force=yes 
           key_file="/home/ec2-user/.ssh/id_rsa_usaspending_config"

# Modify java heap size

    - name: update jvm heap size Xms/Xmx
      become: true
      lineinfile:
        dest: "/etc/elasticsearch/jvm.options"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: "^-Xms.*",
            line: "-Xms15g" }

        - { regexp: "^-Xmx.*",
            line: "-Xmx15g" }

# Disable swap 

    - name: disable swap on the filesystem
      become: true
      shell: swapoff -av 

# Update ulimit

    - name: update ulimit | create directory /etc/systemd/system/elasticsearch.service.d/
      become: true
      file:
        path: /etc/systemd/system/elasticsearch.service.d/
        recurse: true
        state: directory
        mode: 0644

    - name: edit override.conf file to set ulimit nLimitNOFILE=65536 & LimitMEMLOCK=infinity
      become: true
      copy: 
        content: "[Service]\nLimitNOFILE=65536\nLimitMEMLOCK=infinity"
        dest: /etc/systemd/system/elasticsearch.service.d/override.conf

    - name: update ulimit | check file exists
      become: true
      stat: 
        path="/etc/systemd/system/elasticsearch.service.d/override.conf"
      register: file_path

    - name: reload daemon
      become: true
      shell: systemctl daemon-reload

# Update log size from 128 to 256MB
        
    - name: update log rolling size
      become: true
      lineinfile:
        dest: "/etc/elasticsearch/log4j2.properties"
        regexp: '^appender.rolling.policies.size.size =.*'
        line: "appender.rolling.policies.size.size = 256MB"

# Copy elasticsearch.yml to /etc/elasticsearch/elasticsearch.yml

    - name: copy elasticsearch config
      become: true
      copy:
        src:  "/data-act/config/deploy/elk/elasticsearch_elasticsearch.yml"
        dest: "/etc/elasticsearch/elasticsearch.yml"
        remote_src: true

# Copy filebeat.yml to /etc/filebeat/filebeat.yml

    - name: copy filebeat config
      become: true
      copy:
        src:  "/data-act/config/deploy/elk/elasticsearch_filebeat.yml"
        dest: "/etc/filebeat/filebeat.yml"
        remote_src: true

# Copy nginx conf file to /etc/nginx/nginx.conf

    - name: copy nginx config
      become: true
      copy:
        src:  "/data-act/config/deploy/nginx/nginx_usaspending_elasticsearch.conf"
        dest: "/etc/nginx/nginx.conf"
        remote_src: true

# Copy htpasswd from S3 Bucket

    - name: copy es-admin-credentials from S3 Bucket
      become: true
      shell: "aws s3 cp s3://da-config/usaspending/usaspending-elasticsearch-Prod-htpasswd /etc/nginx/.htpasswd --region us-gov-west-1"

    - name: change mode for /etc/nginx/.htpasswd
      become: true 
      file: 
        path: /etc/nginx/.htpasswd
        mode: 0644

# Enable services:

    - name: enable elasticsearch
      become: true
      shell: systemctl enable elasticsearch

    - name: enable filebeat
      become: true
      shell: systemctl enable filebeat

    - name: enable nginx
      become: true
      shell: systemctl enable nginx

# Restart services:

    - name: restart elasticsearch
      become: true
      shell: systemctl restart elasticsearch

    - name: restart filebeat
      become: true
      shell: systemctl restart filebeat

    - name: restart nginx
      become: true
      shell: systemctl restart nginx

