# Data-Act Playbook for ElasticSearch
# This does not install any ES plugins

---
- hosts: "{{ HOST }}"

  become_method: sudo

  user: ec2-user

  tasks:

    - name: upgrade all packages + security patches
      become: true
      yum: name=* state=latest

    - name: install EPEL and IUS repos
      become: true
      yum: name={{ item }}
      with_items:
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        - https://centos7.iuscommunity.org/ius-release.rpm

    - name: install base packages
      become: true
      yum: name={{ item }}
      with_items:
        - git
        - python-pip
        - ansible
        - mlocate
        - vim
        - telnet
        - wget
        - unzip
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel.x86_64

    - name: install aws cli pip package
      become: true
      pip: name=awscli executable=pip

    - name: install elasticsearch
      become: true
      yum: 
        name=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.1.1.rpm

    - name: Download New Relic Infrastructure
      become: true
      shell: curl -o /etc/yum.repos.d/newrelic-infra.repo https://download.newrelic.com/infrastructure_agent/linux/yum/el/7/x86_64/newrelic-infra.repo

    - name: Update cache for New Relic Infrastructure
      become: true
      shell: yum -q makecache -y --disablerepo='*' --enablerepo='newrelic-infra'

    - name: Install New Relic Infrastructure
      become: true
      yum: name=newrelic-infra

    - name: install filebeat
      become: true
      yum: 
        name=https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.1.1-x86_64.rpm

    - name: install nginx (from nginx repo)
      become: true
      yum: 
        name=http://nginx.org/packages/mainline/centos/7/x86_64/RPMS/nginx-1.13.8-1.el7_4.ngx.x86_64.rpm

    - name: modify setsebool to enable httpd_can_network_connect
      become: true
      shell: setsebool -P httpd_can_network_connect=1

    - name: show timestamp in history (root)
      become: true
      shell: echo 'export HISTTIMEFORMAT="%d/%m/%y %T "' >> ~/.bash_profile

    - name: show timestamp in history (ec2-user)
      shell: echo 'export HISTTIMEFORMAT="%d/%m/%y %T "' >> ~/.bash_profile

    - name: colorize (root)
      become: true
      shell: echo 'export PS1="[\[$(tput sgr0)\]\[\033[38;5;1m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\[$(tput sgr0)\]\[\033[38;5;45m\]\h\[$(tput sgr0)\]\[\033[38;5;15m\] \W]\\$ \[$(tput sgr0)\]"' >> ~/.bash_profile

    - name: colorize (ec2-user)
      shell: echo 'export PS1="[\[$(tput sgr0)\]\[\033[38;5;11m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\[$(tput sgr0)\]\[\033[38;5;45m\]\h\[$(tput sgr0)\]\[\033[38;5;15m\] \W]\\$ \[$(tput sgr0)\]"' >> ~/.bash_profile

