---
- hosts: "{{ HOST }}"
  user: ec2-user
  roles: 
    - yum-installs
    - pull-repo
    - pip-install
    - copy-files
    - update-schema
    - start-server
    - new-relic
  environment:
    env: "{{ ENV }}"
