
---
- name: start filebeat
  shell: systemctl start filebeat
  sudo: true
- service: name=rabbitmq-server state=started
  sudo: true
- rabbitmq_user: user={{ rmqUser }}
                 password={{ rmqPass }}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
  sudo: true
- name: start celery tasks
  shell: celery -A jobQueue worker --loglevel=info --logfile=/tmp/job-queue.log --concurrency=10 --detach
  environment:
    PYTHONPATH: "/data-act/backend"
    env: "{{ ENV }}"
  args:
    chdir: /data-act/backend/dataactcore/utils/
  sudo: true