---
- shell: supervisord -c /data-act/web-api/dataactbroker/config/supervisord.conf &
  environment:
    PYTHONPATH: "{{ ansible_env.PYTHONPATH }}:/data-act/core:/data-act/web-api"
  args:
    chdir: /data-act/web-api/dataactbroker/
