---
- shell: nginx
- shell: uwsgi --ini broker_configuration.ini &
  environment:
    PYTHONPATH: "{{ ansible_env.PYTHONPATH }}:/data-act/core:/data-act/web-api"
  args:
    chdir: /data-act/web-api/dataactbroker/uwsgi/
