---
- shell: /opt/logstash/bin/logstash -f /data-act/data-act-logging.conf &
- name: start filebeat
  shell: systemctl stop filebeat
  sudo: true
  ignore_errors: yes
- name: start filebeat
  shell: systemctl start filebeat
  sudo: true
- shell: setsebool -P httpd_can_network_connect=1
  sudo: true
- name: create app log if it doesn't exist
  shell: touch /data-act/app.json-log
  ignore_errors: yes
- name: set owner of app log to ec2-user
  shell: chown ec2-user /data-act/app.json-log
  sudo: true
- shell: pkill supervisord
  sudo: true
  ignore_errors: yes
- shell: supervisord -c /data-act/backend/dataactbroker/config/supervisord.conf &
  sudo: true
  environment:
    PYTHONPATH: "/data-act/backend"
    env: "{{ ENV }}"
  args:
    chdir: /data-act/backend/dataactbroker/
