---

- name: install git
  yum: name=git
- name: install postgres libraries
  yum: name=postgresql94-devel.x86_64
- name: install gcc
  yum: name=gcc
- name: install emacs
  yum: name=emacs
- name: install libffi-devel
  yum: name=libffi-devel