---
- shell: supervisord -c /data-act/validator/dataactvalidator/config/supervisord.conf &
  environment:
    PYTHONPATH: "{{ ansible_env.PYTHONPATH }}:/data-act/core:/data-act/validator"
  args:
    chdir: /data-act/validator/dataactvalidator/
