---
- hosts: "{{ HOST }}"
  user: ec2-user
  become_method: sudo
  roles:
  - pull-repo
  - install-requirements
  vars:
    REPO: https://github.com/fedspendingtransparency/data-act-broker-backend.git

