---
- hosts: all
  remote_user: ec2-user
  become_method: sudo

  vars:
    REPO: https://github.com/fedspendingtransparency/data-act-broker-backend.git
    BRANCH: "{{ BRANCH }}"
    ansible_python_interpreter: /usr/bin/python
    DATADOG_YML_PATH: "/data-act/config/datadog/datadog.yaml"
    DATADOG_KEY_PATH: "/data-act/config/datadog_key"

  tasks:

    - name: Get boto3/botocore for aws modules
      become: true
      pip:
        name: ['boto3', 'botocore']
        executable: pip2

    # ===================== Copy Git Creds from S3 Bucket =====================#

    - name: Pull repo - copy broker git credentials from S3 Bucket
      aws_s3:
        bucket: da-config
        object: /broker/id_rsa_broker_config
        dest: /home/ec2-user/.ssh/id_rsa_broker_config
        region: us-gov-west-1
        mode: get

    - name: Read only permissions for broker git credentials
      become: true
      file:
        path: /home/ec2-user/.ssh/id_rsa_broker_config
        mode: 0400

    # ========================= Git Checkout ========================#

    - name: Checkout backend from git
      become: true
      git:
        repo: "{{ REPO }}"
        version: "{{ BRANCH }}"
        dest: "/data-act/backend"
        accept_hostkey: true
        force: "yes"

    - name: Checkout broker config from git
      become: true
      git:
        repo: git@github.com:fedspendingtransparency/data-act-broker-config.git
        dest: /data-act/config
        accept_hostkey: true
        force: "yes"
        key_file: /home/ec2-user/.ssh/id_rsa_broker_config

    - name: Checkout build-tools repo from git
      become: true
      git:
        repo: git@github.com:fedspendingtransparency/data-act-build-tools.git
        dest: /data-act/build-tools
        accept_hostkey: true
        force: "yes"
        key_file: /home/ec2-user/.ssh/id_rsa_broker_config

    - name: Assign ownership of api to ec2-user
      become: true
      file:
        path: /data-act/
        owner: ec2-user
        recurse: "yes"

    - name: Assign ownership of tmp to ec2-user
      become: true
      file:
        path: /tmp
        owner: ec2-user
        recurse: "yes"

    # ======================== Install PIP Packages ========================#

    - name: Install backend packages based on requirements.txt
      become: true
      pip:
        chdir: /data-act/backend
        requirements: requirements.txt
        executable: pip3.5

    - name: Install server packages based on server_requirements.txt
      become: true
      pip:
        chdir: /data-act/backend
        requirements: server_requirements.txt
        executable: pip3.5

    - name: Install python packages based on legacy_requirements.txt
      become: true
      pip:
        chdir: /data-act/backend
        requirements: legacy_requirements.txt
        executable: pip2

    # ======================== Configure DataDog Key ========================#

    # - name: set datadog variables
    #   vars:
    #     DATADOG_YML_PATH: "/data-act/config/datadog/datadog.yaml"
    #     DATADOG_KEY_PATH: "/data-act/config/datadog_key"

    - name: copy datadog_key from S3
      become: true
      aws_s3:
        bucket: da-config
        object: /shared/datadog_key
        dest: "{{ DATADOG_KEY_PATH }}"
        region: us-gov-west-1
        mode: get

    - name: save the contents of datadog_key file
      shell: cat "{{ DATADOG_KEY_PATH }}"
      register: dd_key

    - name: add Datadog license key to datadog.yaml
      lineinfile:
        dest: "{{ DATADOG_YML_PATH }}"
        regexp: '\s*api_key: .*'
        line: "api_key: {{ dd_key.stdout }}"

    - name: copy datadog.yml to its home location
      become: true
      copy:
        src: "{{ DATADOG_YML_PATH }}"
        dest: /etc/datadog-agent/datadog.yaml
        remote_src: true
