# Base Ansible to run on a fresh FRONTEND RHEL7 install.
# Installs USASpending API dependencies that are mutal across environments.

# TODO: This does not include newrelic infrastructure setup
# This does not include the necessary certs and RDS keys to run the API

---
- hosts: "{{ HOST }}"

  become_method: sudo

  user: ec2-user

  tasks:

    - name: upgrade all packages
      become: true
      yum: name=* state=latest

    - name: install EPEL and IUS repos
      become: true
      yum: name={{ item }}
      with_items:
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        - https://centos7.iuscommunity.org/ius-release.rpm

    - name: install base dependencies
      become: true
      yum: name={{ item }}
      with_items:
        - git
        - java-1.8.0-openjdk
        - nginx
        - unzip
        - wget
        - zlib-devel
        - locate
        - vim
        - telnet
        
    - name: install nginx (from nginx repo)
      become: true
      yum: 
        name=http://nginx.org/packages/mainline/centos/7/x86_64/RPMS/nginx-1.13.8-1.el7_4.ngx.x86_64.rpm

    - name: install aws cli pip package
      become: true
      pip: name=awscli executable=pip3.5

    - name: pull data act build tools repo
      git: repo=https://github.com/fedspendingtransparency/data-act-build-tools.git
           version=master
           dest=/home/ec2-user/data-act-build-tools

    - name: install filebeat
      become: true
      yum: name={{ item }}
      with_items:
        - filebeat
    
    - name: disable requiretty
      become: true
      lineinfile: 
        dest=/etc/sudoers 
        regexp="Defaults\s+requiretty"
        line="# Defaults requiretty"
      
