# Base Ansible to run on a fresh RHEL7 install.
# Installs USASpending API dependencies that are mutal across environments.

# TODO: This does not include newrelic infrastructure setup
# This does not include the necessary certs and RDS keys to run the API

---
- hosts: "{{ HOST }}"

  become_method: sudo

  user: ec2-user

  tasks:

    - name: upgrade all packages
      become: true
      yum: name=* state=latest

    - name: install EPEL and IUS repos
      become: true
      yum: name={{ item }}
      with_items:
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        - https://centos7.iuscommunity.org/ius-release.rpm

    - name: install base dependencies
      become: true
      yum: name={{ item }}
      with_items:
        - ansible
        - gcc
        - gcc-c++
        - git
        - java-1.8.0-openjdk
        - libffi-devel
        - libmemcached
        - memcached
        - nginx
        - pcre.x86_64
        - pcre-devel.x86_64
        - postgresql-devel.x86_64
        - python-devel.x86_64
        - python-pip
        - python35u
        - python35u-devel 
        - python35u-libs
        - python35u-pip
        - unzip
        - wget
        - zlib-devel
        - locate
        - vim
        - telnet

    - name: install libmemcached-devel (from CentOS repo)
      become: true
      yum: 
        name=http://mirror.centos.org/centos/7/os/x86_64/Packages/libmemcached-devel-1.0.16-5.el7.x86_64.rpm
        
    - name: install nginx (from nginx repo)
      become: true
      yum: 
        name=http://nginx.org/packages/mainline/centos/7/x86_64/RPMS/nginx-1.13.8-1.el7_4.ngx.x86_64.rpm

    - name: install aws cli pip package
      become: true
      pip: name=awscli executable=pip3.5
      
    - name: install newrelic
      become: true
      pip: name=newrelic executable=pip3.5

    - name: pull data act build tools repo
      git: repo=https://github.com/fedspendingtransparency/data-act-build-tools.git
           version=master
           dest=/home/ec2-user/data-act-build-tools

    - name: copy filebeat repo info
      become: true
      copy:
        src:  "/home/ec2-user/data-act-build-tools/elastic-beats.repo"
        dest: "/etc/yum.repos.d/elastic-beats.repo"
        remote_src: true

    - name: install filebeat
      become: true
      yum: name={{ item }}
      with_items:
        - filebeat
    
    - name: disable requiretty
      become: true
      lineinfile: 
        dest=/etc/sudoers 
        regexp="Defaults\s+requiretty"
        line="# Defaults requiretty"
      
