---
- hosts: usaspending_frontend_{{ ENV }}
  user: ec2-user
  become_method: sudo

# Requires: BUILD_ID, ENV, and DOMAIN

  tasks:
    - name: remove old frontend backed up files
      become: true
      shell: "rm -rf /var/www-old"
      ignore_errors: yes

    - name: backup old frontend served files
      become: true
      shell: "mv /var/www /var/www-old" 
      ignore_errors: yes

    - name: copy frontend files
      become: true
      shell: "aws s3 cp s3://ds-website-assets/{{ ENV }}/{{ BUILD_ID }}/public/ /var/www --region us-gov-west-1 --recursive"

    - name: checkout config from git
      become: true
      git: repo=git@github.com:fedspendingtransparency/usaspending-config.git 
           dest=/data-act/config 
           accept_hostkey=true 
           force=yes 
           key_file="/home/ec2-user/.ssh/id_rsa_usaspending_config"

    - name: add server name to nginx config
      become: true
      lineinfile:
        dest: /data-act/config/deploy/nginx/nginx_usaspending_frontend.conf
        regexp: '\s*server_name.*;'
        line: "\tserver_name {{ DOMAIN }};"
    
    - name: remove basic auth check from prod
      become: true
      when: ENV == 'prod'
      lineinfile:
        dest: /data-act/config/deploy/nginx/nginx_usaspending_frontend.conf
        regexp: '\s*auth_basic "Basic Auth Check".*'
        state: absent
    
    - name: remove basic auth file from prod
      become: true
      when: ENV == 'prod'
      lineinfile:
        dest: /data-act/config/deploy/nginx/nginx_usaspending_frontend.conf
        regexp: '\s*auth_basic_user_file /etc/nginx/.*'
        state: absent
    
    - name: remove caching from non-prod environments
      become: true
      when: ENV != 'prod'
      lineinfile:
        dest: /data-act/config/deploy/nginx/nginx_usaspending_frontend.conf
        regexp: '\s*add_header Cache-Control.*'
        state: absent
    
    - name: copy ENV config
      become: true
      shell: cp /data-act/config/deploy/nginx/nginx_usaspending_frontend.conf /etc/nginx/nginx.conf

    - name: modify SELinux sebool for httpd_can_network_connect
      become: true
      command: setsebool -P httpd_can_network_connect on

    - name: run restorecon on /var/www/
      become: true
      command: restorecon -R -v /var/www/

    - name: enable nginx service
      become: true
      shell: systemctl enable nginx

    - name: restart nginx service
      become: true
      shell: systemctl restart nginx
