# Base Ansible to run on a fresh RHEL7 install.
# Installs USASpending API dependencies that are mutal across environments.

---
- hosts: "{{ HOST }}"

  vars:
    NR_KEY: "{{ lookup('file', '/etc/nr_key') }}"

  become_method: sudo

  user: ec2-user

  tasks:

    - name: upgrade all packages
      become: true
      yum: name=* state=latest

    - name: install EPEL and IUS repos
      become: true
      yum: name={{ item }}
      with_items:
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        - https://centos7.iuscommunity.org/ius-release.rpm

    - name: install base dependencies
      become: true
      yum: name={{ item }}
      with_items:
        - ansible
        - gcc
        - gcc-c++
        - git
        - java-1.7.0-openjdk
        - libffi-devel
        - libmemcached
        - memcached
        - nginx
        - pcre.x86_64
        - pcre-devel.x86_64
        - postgresql-devel.x86_64
        - python-devel.x86_64
        - python-pip
        - python35u
        - python35u-devel 
        - python35u-libs
        - python35u-pip
        - unzip
        - wget
        - zlib-devel

    - name: install libmemcached-devel (from CentOS repo)
      become: true
      yum: 
        name=http://mirror.centos.org/centos/7/os/x86_64/Packages/libmemcached-devel-1.0.16-5.el7.x86_64.rpm

    - name: install aws cli pip package
      become: true
      pip: name=awscli executable=pip3.5
      
    - name: install newrelic
      become: true
      pip: name=newrelic executable=pip3.5
      
    - name: add newrelic license key
      lineinfile:
        dest: "{{ CODE_HOME }}/config/newrelic.ini"
        regexp: '\s*license_key =.*'
        line: "license_key = '{{ NR_KEY }}'"

    - name: pull data act build tools repo
      git: repo=https://github.com/fedspendingtransparency/data-act-build-tools.git
           version=master
           dest=/home/ec2-user/data-act-build-tools

    - name: copy filebeat repo info
      become: true
      copy:
        src:  "/home/ec2-user/data-act-build-tools/elastic-beats.repo"
        dest: "/etc/yum.repos.d/elastic-beats.repo"
        remote_src: true

    - name: copy logstash repo info
      become: true
      shell: "{{ item }}"
      with_items:
        - "rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch" 
        - "cp /home/ec2-user/data-act-build-tools/logstash.repo /etc/yum.repos.d/logstash.repo"

    - name: install filebeat and logstash
      become: true
      yum: name={{ item }}
      with_items:
        - filebeat
        - logstash
    
    - name: disable requiretty
      become: true
      lineinfile: 
        dest=/etc/sudoers 
        regexp="Defaults\s+requiretty"
        line="# Defaults requiretty"
      
