---

- shell: "aws s3 cp s3://{{ ENV }}-data-act-submission/config/config.yml /data-act/backend/dataactcore/config.yml --region us-gov-west-1"
  sudo: true
- shell: "aws s3 cp s3://{{ ENV }}-data-act-submission/config/nginx_{{ APP }}.conf /etc/nginx/nginx.conf --region us-gov-west-1"
  sudo: true
- shell: "aws s3 cp s3://{{ ENV }}-data-act-submission/config/filebeat-{{ ENV }}-{{ APP }}.yml /etc/filebeat/filebeat.yml --region us-gov-west-1"
  sudo: true
- shell: "aws s3 cp s3://{{ ENV }}-data-act-submission/config/data-act-logging-validator.conf /data-act/data-act-logging.conf --region us-gov-west-1"
  sudo: true

- name: copy cert.pem
  shell: "cp /{{ PATH }}/cert_{{ ENV }}.pem /{{ PATH }}/cert.pem"
  sudo: true
- name: copy cert.key
  shell: "cp /{{ PATH }}/cert_{{ ENV }}.key /{{ PATH }}/cert.key"
  sudo: true

- name: assign ownership of cert.pem to ec2-user
  sudo: true
  file: path=/{{ PATH }}/cert.pem owner=ec2-user
- name: assign ownership of cert.key to ec2-user
  sudo: true
  file: path=/{{ PATH }}/cert.key owner=ec2-user