---
- shell: "aws s3 cp s3://{{ ENV }}-data-act-submission/config/dbCred.json /data-act/core/dataactcore/credentials/dbCred.json"

- shell: "aws s3 cp s3://{{ ENV }}-data-act-submission/config/s3bucket.json /data-act/core/dataactcore/aws/s3bucket.json"

- shell: "aws s3 cp s3://{{ ENV }}-data-act-submission/config/logging.json /data-act/core/dataactcore/utils/logging.json"

- shell: "aws s3 cp s3://{{ ENV }}-data-act-submission/config/nginxVal.conf /etc/nginx/nginx.conf"

- shell: "aws s3 cp s3://{{ ENV }}-data-act-submission/config/validator_configuration.json /data-act/validator/dataactvalidator/validator_configuration.json"