---
 - name: Install API packages based on requirements.txt.
   sudo: true
   pip: chdir=/data-act/backend requirements="requirements.txt" executable=pip3
 - name: Install server packages based on server_requirements.txt.
   sudo: true
   pip: chdir=/data-act/backend requirements="server_requirements.txt" executable=pip2
