---

- name: core schema update (api)
  when: APP == 'broker'
  shell: python3 /data-act/backend/dataactcore/scripts/initialize.py -db -r -v
  sudo: true
  environment:
    PYTHONPATH: "/data-act/backend"
    env: "{{ ENV }}"
  args:
    chdir: /data-act/backend/dataactbroker/scripts/

- name: core schema update (validator)
  when: APP == 'validator'
  shell: python3 /data-act/backend/dataactcore/scripts/initialize.py -db -r -v
  sudo: true
  environment:
    PYTHONPATH: "/data-act/backend"
    env: "{{ ENV }}"
  args:
    chdir: /data-act/backend/dataactvalidator/scripts/
